### ISSUE TITLE
Narrow `measure_total` scope of measurement to just the interpreter loop

### ISSUE THREAD

**Issue by pdobacz** [imapp-pl/gas-cost-estimator#66]
Currently these two commands give same results:

```
sudo docker run   --rm   --privileged --security-opt seccomp:unconfined -v /home/ubuntu/pdobacz/imapp/local:/srv/local  -it gas-cost-estimator/geth_total sh -c "cd src && python3 program_generator/pg_arythmetic.py generate --count=10 --opsLimit 2 --fullCsv | python3 instrumentation_measurement/measurements.py measure --evm geth --mode total --sampleSize=300 --nSamples=1 2>/dev/null"
```
```
sudo docker run   --rm   --privileged --security-opt seccomp:unconfined -v /home/ubuntu/pdobacz/imapp/local:/srv/local  -it gas-cost-estimator/geth_total sh -c "cd src && python3 program_generator/pg_arythmetic.py generate --count=10 --opsLimit 20 --fullCsv | python3 instrumentation_measurement/measurements.py measure --evm geth --mode total --sampleSize=300 --nSamples=1 2>/dev/null"
```

the measured `runtime.Excecute` probably contains too much EVM setup irrelevant to the OPCODE measurements

**Comment by pik694** [comment]
@pdobacz I believe you used a wrong flag to generate the program - `pg_arithmetic` has `gasLimit` instead of `opsLimit` and you skipped the stderr output that's why you did not see `pg_arithemtic` complaining 😉 

There is also a default value for `gasLimit`, which means why it did generate a program https://github.com/imapp-pl/gas-cost-estimator/blob/3736a63a758ded8c3ed72c613be285bf026a4cfa/src/program_generator/pg_arythmetic.py#L59


When I run it with `gasLimit=1000` and `gasLimit=1000` it did give me different results - though the result the time does not raise 10 times as the `gasLimit`. Please see the attached results
[result_1000.csv](https://github.com/imapp-pl/gas-cost-estimator/files/7565763/result_1000.csv)
[result_10000.csv](https://github.com/imapp-pl/gas-cost-estimator/files/7565765/result_10000.csv)

**Comment by pdobacz** [comment]
@pik694 I used the `origin/lglen/pg_arithmetic3` branch where `opsLimit` is supported

**Comment by pdobacz** [comment]
I'm guessing that gasLimit of 1000 and 10000 yields longer programs than opsLimit 2 or 20, which is why your results vary. During my recent attempts to approach the validation, I figured it would be useful to compare shorter programs, hence the idea to narrow the scope.
